### ISSUE TITLE
collecting relevant data for constants

### ISSUE THREAD

**Issue by jlopp** [jlopp/bitcoin-transaction-size-calculator#1]
Different types of scripts will create different sizes and weights.

https://bitcoin.stackexchange.com/questions/1195/how-to-calculate-transaction-size-before-sending-legacy-non-segwit-p2pkh-p2sh/46379#46379

https://github.com/kristapsk/bitcoin-scripts/blob/0b847bec016638e60313ecec2b81f2e8accd311b/inc.common.sh#L17

https://twitter.com/murchandamus/status/1262062602298916865

**Comment by jlopp** [comment]
https://github.com/BitGo/unspents/blob/c9be439be9a330bcead617bde16ad8a750b524fc/src/dimensions.ts

https://bitcoin.stackexchange.com/questions/30570/predict-multi-signature-transaction-size

https://github.com/blocktrail/blocktrail-sdk-php/blob/master/src/SizeEstimation.php

**Comment by 0xB10C** [comment]
@harding build something similar earlier this year which includes detailed size constants.

https://github.com/bitcoinops/bitcoinops.github.io/pull/322

**Comment by jlopp** [comment]
Great; thanks. https://bitcoinops.org/en/tools/calc-size
