### ISSUE TITLE
SegWit transactions have two witness bytes overhead

### ISSUE THREAD

**Issue by murchandamus** [jlopp/bitcoin-transaction-size-calculator#2]
Segwit transactions add two witness bytes in the header: marker and flag. Since they are in the witness, it only add two WU to the transaction.

https://github.com/jlopp/bitcoin-transaction-size-calculator/blob/ac1fcb9ed344627ee6773d218d71f8cbc878e7fb/index.html#L118

**Comment by jlopp** [comment]
OK so you're saying it add 0 virtual bytes, 2 raw bytes, 2 WU?

**Comment by murchandamus** [comment]
More or less. The virtualsize of a transaction is only calculated once across all of it in the end. So, you could estimate the transaction header with 11 vbytes, but it would be more accurate to calculate with 42WU or 10.5 vbytes and only round up the virtualsize once for the whole transaction.
