### ISSUE TITLE
[Question]Does this calculator work for generic scripts?

### ISSUE THREAD

**Issue by educob** [jlopp/bitcoin-transaction-size-calculator#3]
Hello.

Let's say I have a multisignature script or even a genreric one (whith IF-ELSE, ...). Does this calculator work for these scripts also?

Thanks.

**Comment by jlopp** [comment]
I'm only really able to support standard multisig scripts; anything more complex becomes difficult to model. I think the only way to support more complex scripts would be to add support for someone to paste in an arbitrarily complex redeem script and have the calculator determine how many bytes it is.

**Comment by harding** [comment]
For script size calculations, you can use the Miniscript demo http://bitcoin.sipa.be/miniscript/ , which returns the average script size (the actual size will vary in contracts using conditionals like `OP_IF` depending on which branches you take).

**Comment by educob** [comment]
Thanks. My web service creates generic scripts so I'd need to know how to compute tx size knowing the redeem script bytes.
Sometimes I send bitcoins to a generic script sometime I spend funds from this script. 
Thanks.
