### ISSUE TITLE
Overhead calculation missing witness element count

### ISSUE THREAD

**Issue by sedited** [jlopp/bitcoin-transaction-size-calculator#4]
Bitcoin Optech has 0.25 vbytes more in their segwit transaction overhead weight calculation. As explained in `Witness element count (compactSize/4) The number of witness elements included in the transaction. 0.25 vbytes for up to 252 elements`. I only see references to the segwit marker in your code though, but not the additional size parameter, or am I missing something?

**Comment by jlopp** [comment]
Good catch; I think I've fixed that oversight now.
