### ISSUE TITLE
[BRC20 inscribe fee calculate]

### ISSUE THREAD

**Issue by weixuefeng** [jlopp/bitcoin-transaction-size-calculator#9]
https://mempool.space/tx/a73f9f187dc336d6c1594421d3b81e6753854dd340629d9197525d54be2b24b4

calculate is 130, but real is 161.5

**Comment by jlopp** [comment]
Indeed; it's not possible for the calculator to know the size of transactions that have arbitrary witness data added to them for meta protocols like tokens and inscriptions.
